//
//  MovieDetailPresenter.swift
//  RappiMovies
//
//  Created by Juan on 11/11/18.
//  Copyright (c) 2018 Juand. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic{
    func presentMovieInDetail(response: MovieDetail.Load.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic{
    weak var viewController: MovieDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentMovieInDetail(response: MovieDetail.Load.Response){
        let viewModel = MovieDetail.Load.ViewModel(videoID : response.videoID )
        viewController?.displayVideo(viewModel: viewModel)
    }
}
