//
//  MovieDetailInteractor.swift
//  RappiMovies
//
//  Created by Juan on 11/11/18.
//  Copyright (c) 2018 Juand. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic{
    func doLoadInitialData(request: MovieDetail.Load.Request)
}

protocol MovieDetailDataStore{
    var movie: MovieModel { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore{
   
    var movie: MovieModel = MovieModel()
    
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doLoadInitialData(request: MovieDetail.Load.Request){
        worker = MovieDetailWorker()
        
        worker?.fetchMovieID(movieID: request.movieID
            , completitionHandler: { (videoID, error) in
           
            let response = MovieDetail.Load.Response(videoID: videoID)
            self.presenter?.presentMovieInDetail(response: response)
                
        })
        
     
    }
}
