//
//  MainMoviesInteractor.swift
//  RappiMovies
//
//  Created by Juan on 11/11/18.
//  Copyright (c) 2018 Juand. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMoviesBusinessLogic {
    func doLoadInitialData(request: MainMovies.Load.Request)
    func doLoadDetailView(reques: MainMovies.Detail.Request)
}

protocol MainMoviesDataStore {
    var movie: MovieModel { get set }
}

class MainMoviesInteractor: MainMoviesBusinessLogic, MainMoviesDataStore {
    
    var movie: MovieModel = MovieModel()
    
    func doLoadDetailView(reques: MainMovies.Detail.Request) {
        
        let movieSelected = reques.movie
        self.movie = movieSelected
        let response = MainMovies.Detail.Response()
        presenter?.presentDetail(response: response)
        
    }
    
    var presenter: MainMoviesPresentationLogic?
    var worker: MainMoviesWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doLoadInitialData(request: MainMovies.Load.Request){
        worker = MainMoviesWorker()
        let category = request.selectedCategory
        worker?.fetchMovies( selectedCat: category, completitionHandler: { (movies, error) in
            let response = MainMovies.Load.Response(movies: movies)
            self.presenter?.presentInitialData(response: response)
        })
        
    }
}
