//
//  MainMoviesRouter.swift
//  RappiMovies
//
//  Created by Juan on 11/11/18.
//  Copyright (c) 2018 Juand. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainMoviesRoutingLogic{
    func routeToDetail()
}

protocol MainMoviesDataPassing{
    var dataStore: MainMoviesDataStore? { get }
}

class MainMoviesRouter: NSObject, MainMoviesRoutingLogic, MainMoviesDataPassing {
   
    
    weak var viewController: MainMoviesViewController?
    var dataStore: MainMoviesDataStore?
    
    // MARK: Routing
    
    func routeToDetail() {
        let destinaitionVC = MovieDetailViewController()
        //Destination Data Store
        var destinationDS = destinaitionVC.router!.dataStore!
        
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinaitionVC)
    }
    
    // MARK: Navigation
    
    func navigateToDetail(source: MainMoviesViewController, destination: MovieDetailViewController){
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(source: MainMoviesDataStore, destination: inout MovieDetailDataStore){
      destination.movie = source.movie
    }
}
