//
//  MainMoviesWorker.swift
//  RappiMovies
//
//  Created by Juan on 11/11/18.
//  Copyright (c) 2018 Juand. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesWorker {
    func fetchMovies(selectedCat : Int,completitionHandler : @escaping ( ([MovieModel], Error?) -> Void ) )
    
}

class MainMoviesWorker : MoviesWorker {
   
    func fetchMovies(selectedCat : Int,completitionHandler : @escaping ( ([MovieModel], Error?) -> Void ) ){

        Services.shared.fetchMovies(selectedCategory: selectedCat) { (movies, error) in
            completitionHandler(((movies) ?? nil)!, error)
        }
        
    }
    
}
